# Generated by Django 4.2.9 on 2024-01-18 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integrator_type', models.CharField(choices=[('UN', 'Unknown'), ('PP', 'Payment Service Provider'), ('MC', 'Merchant'), ('PR', 'Processor')], default='UN', max_length=2)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=250)),
                ('owner', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_signed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Integrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('company_address', models.CharField(blank=True, max_length=500)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=250, unique=True)),
                ('contact_phone_1', models.CharField(blank=True, max_length=50)),
                ('contact_phone_2', models.CharField(blank=True, max_length=50)),
                ('contract', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signee', to='integrators.contract')),
            ],
        ),
    ]
