# Generated by Django 4.2.9 on 2024-01-18 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMVConfiguration',
            fields=[
                ('name', models.CharField(error_messages={'unique': 'This config already exists'}, max_length=50, unique=True)),
                ('scope', models.CharField(choices=[('UN', 'Unknown'), ('MC', 'Mastercard Level 2'), ('VI', 'Visa Level 2'), ('PR', 'Production Level 3')], default='UN', max_length=2)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
